# Exported from Render on 2024-09-14T21:36:33Z
services:
- type: web
  name: PREM-BOT-1
  runtime: node
  repo: https://github.com/prem-project3608/PREM-BOT-1
  plan: free
  region: oregon
  buildCommand: npm install ytdl-core fs-extra yt-search
  startCommand: 'npm start '
version: "1"
